In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics

In [2]:
df = pd.read_csv(r"heart.csv")
df.shape

(303, 14)

In [5]:
X = df.drop(['output'], axis=1)
Y = df['output']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [6]:
from sklearn.preprocessing import StandardScaler
# define min max scaler
scaler = StandardScaler()
# transform data
X_train_scaled = scaler.fit_transform(X_train)

In [7]:
X_train_scaled

array([[-1.35679832,  0.72250438,  0.00809909, ...,  0.95390513,
        -0.68970073, -0.50904773],
       [ 0.38508599,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [-0.92132724,  0.72250438,  0.98808912, ..., -0.69498803,
        -0.68970073, -0.50904773],
       ...,
       [ 1.58263146,  0.72250438,  1.96807914, ..., -0.69498803,
         0.32186034, -0.50904773],
       [-0.92132724,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [ 0.92942484, -1.38407465,  0.00809909, ...,  0.95390513,
         1.33342142, -0.50904773]])

In [8]:
X_test_scaled = scaler.fit_transform(X_test)
X_test_scaled

array([[ 3.51938054e-01,  5.20416500e-01, -8.17224232e-01,
         6.92350698e-01,  6.70698758e-01, -5.45776823e-01,
        -8.61891607e-01, -1.43822060e+00,  1.28536917e+00,
        -3.99335669e-01, -4.85744493e-01,  7.31507170e-02,
        -2.00597821e+00],
       [ 5.85288285e-01,  5.20416500e-01,  2.00451227e+00,
         1.72875297e+00,  9.21953360e-01, -5.45776823e-01,
        -8.61891607e-01,  4.50638062e-01, -7.77986605e-01,
        -6.92823330e-01, -4.85744493e-01, -8.19288030e-01,
         9.42568077e-01],
       [ 3.51938054e-01,  5.20416500e-01,  1.06393343e+00,
         6.92350698e-01, -2.46998376e+00,  1.83225076e+00,
         1.16023870e+00,  1.01327681e+00, -7.77986605e-01,
        -6.92823330e-01,  1.07375098e+00,  7.31507170e-02,
         9.42568077e-01],
       [ 2.35262938e-01, -1.92153785e+00, -8.17224232e-01,
        -1.36771119e-01,  3.45543726e+00, -5.45776823e-01,
        -8.61891607e-01,  8.89417229e-02,  1.28536917e+00,
         5.54499228e-01, -4.85744493e

In [18]:
from sklearn.svm import SVC
svm_linear = SVC(kernel='linear', C=0.01)
svm_linear.fit(X_train_scaled, y_train)
print("*** Linear kernel ***")
print("Accuracy:", svm_linear.score(X_train_scaled, y_train))

# Predict on the training set
y_train_pred = svm_linear.predict(X_train_scaled)

# Predict on the testing set
y_test_pred = svm_linear.predict(X_test_scaled)

# Calculate training accuracy
train_accuracy = accuracy_score(y_train, y_train_pred)
print("Training Accuracy:", train_accuracy)

# Calculate testing accuracy
test_accuracy = accuracy_score(y_test, y_test_pred)
print("Testing Accuracy:", test_accuracy)

precision = precision_score(y_test, y_test_pred)
print("Precision:", precision)

recall = recall_score(y_test, y_test_pred)
print("Recall:", recall)

f1 = f1_score(y_test, y_test_pred)
print("F1 Score:", f1)

cm = confusion_matrix(y_test, y_test_pred)
print("Confusion Matrix:")
print(cm)
 

*** Linear kernel ***
Accuracy: 0.8264462809917356
Training Accuracy: 0.8264462809917356
Testing Accuracy: 0.8852459016393442
Precision: 0.8571428571428571
Recall: 0.9375
F1 Score: 0.8955223880597014
Confusion Matrix:
[[24  5]
 [ 2 30]]


In [19]:
svm_degree_2 = SVC(kernel='poly', degree=2)
svm_degree_2.fit(X_train_scaled, y_train)
print("*** Polynomial kernel ***")
print("Accuracy:", svm_degree_2.score(X_train_scaled, y_train))

# Predict on the training set
y_train_pred = svm_degree_2.predict(X_train_scaled)

# Predict on the testing set
y_test_pred = svm_degree_2.predict(X_test_scaled)

# Calculate training accuracy
train_accuracy = accuracy_score(y_train, y_train_pred)
print("Training Accuracy:", train_accuracy)

# Calculate testing accuracy
test_accuracy = accuracy_score(y_test, y_test_pred)
print("Testing Accuracy:", test_accuracy)

precision = precision_score(y_test, y_test_pred)
print("Precision:", precision)

recall = recall_score(y_test, y_test_pred)
print("Recall:", recall)

f1 = f1_score(y_test, y_test_pred)
print("F1 Score:", f1)

cm = confusion_matrix(y_test, y_test_pred)
print("Confusion Matrix:")
print(cm)

*** Polynomial kernel ***
Accuracy: 0.8099173553719008
Training Accuracy: 0.8099173553719008
Testing Accuracy: 0.7377049180327869
Precision: 0.6904761904761905
Recall: 0.90625
F1 Score: 0.7837837837837837
Confusion Matrix:
[[16 13]
 [ 3 29]]


In [20]:
svm_degree_3 = SVC(kernel='rbf')
svm_degree_3.fit(X_train_scaled, y_train)
print("*** RBF kernel ***")
print("Accuracy:", svm_degree_3.score(X_train_scaled, y_train))

# Predict on the training set
y_train_pred = svm_degree_3.predict(X_train_scaled)

# Predict on the testing set
y_test_pred = svm_degree_3.predict(X_test_scaled)

# Calculate training accuracy
train_accuracy = accuracy_score(y_train, y_train_pred)
print("Training Accuracy:", train_accuracy)

# Calculate testing accuracy
test_accuracy = accuracy_score(y_test, y_test_pred)
print("Testing Accuracy:", test_accuracy)

precision = precision_score(y_test, y_test_pred)
print("Precision:", precision)

recall = recall_score(y_test, y_test_pred)
print("Recall:", recall)

f1 = f1_score(y_test, y_test_pred)
print("F1 Score:", f1)

cm = confusion_matrix(y_test, y_test_pred)
print("Confusion Matrix:")
print(cm)

*** RBF kernel ***
Accuracy: 0.9214876033057852
Training Accuracy: 0.9214876033057852
Testing Accuracy: 0.8688524590163934
Precision: 0.8529411764705882
Recall: 0.90625
F1 Score: 0.8787878787878787
Confusion Matrix:
[[24  5]
 [ 3 29]]
