In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.model_selection import train_test_split

In [10]:
df = pd.read_csv(r"heart.csv")
df.shape

(303, 14)

In [11]:
X = df.drop(['output'], axis=1)
Y = df['output']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [13]:
X_train_scaled

array([[-1.35679832,  0.72250438,  0.00809909, ...,  0.95390513,
        -0.68970073, -0.50904773],
       [ 0.38508599,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [-0.92132724,  0.72250438,  0.98808912, ..., -0.69498803,
        -0.68970073, -0.50904773],
       ...,
       [ 1.58263146,  0.72250438,  1.96807914, ..., -0.69498803,
         0.32186034, -0.50904773],
       [-0.92132724,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [ 0.92942484, -1.38407465,  0.00809909, ...,  0.95390513,
         1.33342142, -0.50904773]])

In [14]:
X_test_scaled = scaler.fit_transform(X_test)
X_test_scaled

array([[ 3.51938054e-01,  5.20416500e-01, -8.17224232e-01,
         6.92350698e-01,  6.70698758e-01, -5.45776823e-01,
        -8.61891607e-01, -1.43822060e+00,  1.28536917e+00,
        -3.99335669e-01, -4.85744493e-01,  7.31507170e-02,
        -2.00597821e+00],
       [ 5.85288285e-01,  5.20416500e-01,  2.00451227e+00,
         1.72875297e+00,  9.21953360e-01, -5.45776823e-01,
        -8.61891607e-01,  4.50638062e-01, -7.77986605e-01,
        -6.92823330e-01, -4.85744493e-01, -8.19288030e-01,
         9.42568077e-01],
       [ 3.51938054e-01,  5.20416500e-01,  1.06393343e+00,
         6.92350698e-01, -2.46998376e+00,  1.83225076e+00,
         1.16023870e+00,  1.01327681e+00, -7.77986605e-01,
        -6.92823330e-01,  1.07375098e+00,  7.31507170e-02,
         9.42568077e-01],
       [ 2.35262938e-01, -1.92153785e+00, -8.17224232e-01,
        -1.36771119e-01,  3.45543726e+00, -5.45776823e-01,
        -8.61891607e-01,  8.89417229e-02,  1.28536917e+00,
         5.54499228e-01, -4.85744493e

In [17]:
pip install tensorflow


In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dropout, BatchNormalization

def model():
    model = Sequential()
    model.add(Dense(16, input_dim=13, kernel_initializer='normal', activation='relu'))
    model.add(Dropout(0.2)) 
    model.add(Dense(8, kernel_initializer='normal', activation='relu'))
    model.add(BatchNormalization())  
    model.add(Dense(4, kernel_initializer='normal', activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    adam = Adam(lr=0.001)
    model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
    return model

modell = model()

print(modell.summary())



TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

In [ ]:
modell.fit(X_train_scaled, y_train, epochs=150, batch_size=10, verbose = 1)

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
pred = np.round(modell.predict(X_test_scaled)).astype(int)

print('Results for Model')
print('Accuracy: ', accuracy_score(y_test, pred))
print('Precision:', precision_score(y_test, pred))
print('Recall:', recall_score(y_test, pred))
cm = confusion_matrix(y_test, pred)
print("Confusion Matrix:")
print(cm)

2/2 [==============================] - 0s 16ms/step
Results for Model
Accuracy:  0.8524590163934426
Precision: 0.8285714285714286
Recall: 0.90625
Confusion Matrix:
[[23  6]
 [ 3 29]]
